### ISSUE TITLE
Error's installing on Ubutnu 16.10

### ISSUE THREAD

**Issue by status-five** [naikai/sake#59]
I keep getting this error when I try to install:

```R
> shiny::runApp(system.file("sake", package="sake"))

Listening on http://127.0.0.1:3557
Warning in tag("div", list(...)) :
  restarting interrupted promise evaluation
Warning in tag("div", list(...)) : internal error -3 in R_decompress1
Warning: Error in tag: lazy-load database '/home/dmolik/R/x86_64-pc-linux-gnu-library/3.3/d3heatmap/R/d3heatmap.rdb' is corrupt
Stack trace (innermost first):
    72: tag
    71: tags$div
    70: div
    69: tag
    68: tags$div
    67: div
    66: tag
    65: tags$div
    64: div
    63: box
    62: tag
    61: tags$div
    60: div
    59: conditionalPanel
    58: tag
    57: tags$div
    56: div
    55: fluidRow
    54: tag
    53: tags$div
    52: div
    51: tabItem
    50: lapply
    49: tabItems
    48: tag
    47: tags$section
    46: tag
    45: tags$div
    44: div
    43: dashboardBody
     1: shiny::runApp
Error : lazy-load database '/home/dmolik/R/x86_64-pc-linux-gnu-library/3.3/d3heatmap/R/d3heatmap.rdb' is corrupt
```

When I install the package from the cran repo it goes fine: 

```R
> install.packages("d3heatmap")
Installing package into ‘/home/dmolik/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://ftp.ussg.iu.edu/CRAN/src/contrib/d3heatmap_0.6.1.1.tar.gz'
Content type 'application/x-gzip' length 507140 bytes (495 KB)
==================================================
downloaded 495 KB

* installing *source* package ‘d3heatmap’ ...
** package ‘d3heatmap’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (d3heatmap)

The downloaded source packages are in
	‘/tmp/RtmpLundlR/downloaded_packages’
```

And when I try to install from github, it will not install:

```R
> devtools::install_github("rstudio/d3heatmap")
Downloading GitHub repo rstudio/d3heatmap@master
from URL https://api.github.com/repos/rstudio/d3heatmap/zipball/master
Error in eapply(ns_env(pkg), force, all.names = TRUE) : 
  lazy-load database '/home/dmolik/R/x86_64-pc-linux-gnu-library/3.3/d3heatmap/R/d3heatmap.rdb' is corrupt
In addition: Warning messages:
1: In eapply(ns_env(pkg), force, all.names = TRUE) :
  restarting interrupted promise evaluation
2: In eapply(ns_env(pkg), force, all.names = TRUE) :
  internal error -3 in R_decompress1
```

**Comment by naikai** [comment]
According to this:

https://github.com/wch/movies/issues/3

The internal error -3 often happens when you use install_github to install a package that's currently loaded; try restarting R and running the app again.

Can you please test it and let me know if it fixes the problem?
Thanks.



On Jan 28, 2017, at 4:08 PM, David Molik <notifications@github.com<mailto:notifications@github.com>> wrote:


I keep getting this error when I try to install:

> shiny::runApp(system.file("sake", package="sake"))

Listening on http://127.0.0.1:3557
Warning in tag("div", list(...)) :
  restarting interrupted promise evaluation
Warning in tag("div", list(...)) : internal error -3 in R_decompress1
Warning: Error in tag: lazy-load database '/home/dmolik/R/x86_64-pc-linux-gnu-library/3.3/d3heatmap/R/d3heatmap.rdb' is corrupt
Stack trace (innermost first):
    72: tag
    71: tags$div
    70: div
    69: tag
    68: tags$div
    67: div
    66: tag
    65: tags$div
    64: div
    63: box
    62: tag
    61: tags$div
    60: div
    59: conditionalPanel
    58: tag
    57: tags$div
    56: div
    55: fluidRow
    54: tag
    53: tags$div
    52: div
    51: tabItem
    50: lapply
    49: tabItems
    48: tag
    47: tags$section
    46: tag
    45: tags$div
    44: div
    43: dashboardBody
     1: shiny::runApp
Error : lazy-load database '/home/dmolik/R/x86_64-pc-linux-gnu-library/3.3/d3heatmap/R/d3heatmap.rdb' is corrupt

When I install the package from the cran repo it goes fine:

> install.packages("d3heatmap")
Installing package into ‘/home/dmolik/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://ftp.ussg.iu.edu/CRAN/src/contrib/d3heatmap_0.6.1.1.tar.gz'
Content type 'application/x-gzip' length 507140 bytes (495 KB)
==================================================
downloaded 495 KB

* installing *source* package ‘d3heatmap’ ...
** package ‘d3heatmap’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (d3heatmap)

The downloaded source packages are in
        ‘/tmp/RtmpLundlR/downloaded_packages’

And when I try to install from github, it will not install:

> devtools::install_github("rstudio/d3heatmap")
Downloading GitHub repo rstudio/d3heatmap@master
from URL https://api.github.com<http://api.github.com>/repos/rstudio/d3heatmap/zipball/master
Error in eapply(ns_env(pkg), force, all.names = TRUE) :
  lazy-load database '/home/dmolik/R/x86_64-pc-linux-gnu-library/3.3/d3heatmap/R/d3heatmap.rdb' is corrupt
In addition: Warning messages:
1: In eapply(ns_env(pkg), force, all.names = TRUE) :
  restarting interrupted promise evaluation
2: In eapply(ns_env(pkg), force, all.names = TRUE) :
  internal error -3 in R_decompress1

**Comment by status-five** [comment]
after completely deleting the library and then reinstalling from github ( devtools::install_github("rstudio/d3heatmap") ) it worked like a skookum choocher

**Comment by naikai** [comment]
Great!


On Jan 28, 2017, at 4:12 PM, David Molik <notifications@github.com<mailto:notifications@github.com>> wrote:


after completely deleting the library and then reinstalling from github ( devtools::install_github("rstudio/d3heatmap") ) it worked like a skookum choocher
